# Generated by Django 5.0 on 2023-12-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.TextField(choices=[('MATH', 'Math Game'), ('ANAGRAM', 'Anagram Game')], default='MATH'),
        ),
    ]
